SVHN specific configuration

dataset:
  name: 'svhn'
  input_dim: 3072  # 32x32x3
  num_classes: 10
  data_path: './data/svhn'

training:
  batch_size: 128
  epochs: 150
  learning_rate: 0.02
  weight_decay: 0.0002
  momentum: 0.9
  optimizer: 'sgd'

defense:
  alpha: 0.12
  beta: 0.04
  sigma_max: 1.1
  lambda_param: 0.28

attacks:
  - 'mrm'
  - 'fes_mia'
  - 'imia'

evaluation:
  num_shadow_models: 5
  test_size: 0.2
  random_state: 42
  metrics: ['accuracy', 'precision', 'recall', 'f1']
